### PR TITLE
Elasticsearch 8.0 support

### PR DESCRIPTION
**Pull request by hkulekci**
Here the list of changes : 

## Aggregation 

 - [x] Percentiles aggregation: disallow specifying same percentile values twice [#52257](https://github.com/elastic/elasticsearch/pull/52257) (issue: [#51871](https://github.com/elastic/elasticsearch/issues/51871))
 - [x] Remove Adjacency_matrix setting [#46327](https://github.com/elastic/elasticsearch/pull/46327) (issues: [#46257](https://github.com/elastic/elasticsearch/issues/46257), [#46324](https://github.com/elastic/elasticsearch/issues/46324))
 - [x] Remove MovingAverage pipeline aggregation [#39328](https://github.com/elastic/elasticsearch/pull/39328)
 - [x] Remove deprecated _time and _term sort orders [#39450](https://github.com/elastic/elasticsearch/pull/39450)
 - [x] Remove deprecated date histo interval [#75000](https://github.com/elastic/elasticsearch/pull/75000)

## Geo 

 - [x] Disallow creating geo_shape mappings with deprecated parameters [#70850](https://github.com/elastic/elasticsearch/pull/70850) (issue: [#32039](https://github.com/elastic/elasticsearch/issues/32039))
 - [x] Remove bounding box query type parameter [#74536](https://github.com/elastic/elasticsearch/pull/74536)

 ## Infra REST API

 - [x] Remove content type required setting [#61043](https://github.com/elastic/elasticsearch/pull/61043)
 - [x] Allow parsing Content-Type and Accept headers with version [#61427](https://github.com/elastic/elasticsearch/pull/61427)
 
 
 ## Search 
 

 - [x] Fix range query on date fields for number inputs [#63692](https://github.com/elastic/elasticsearch/pull/63692) (issue: [#63680](https://github.com/elastic/elasticsearch/issues/63680))
 - [x] Parse empty first line in msearch request body as action metadata [#41011](https://github.com/elastic/elasticsearch/pull/41011) (issue: [#39841](https://github.com/elastic/elasticsearch/issues/39841))
 - [x] Remove CommonTermsQuery and cutoff_frequency param [#42654](https://github.com/elastic/elasticsearch/pull/42654) (issue: [#37096](https://github.com/elastic/elasticsearch/issues/37096))
 - [x] Remove type query [#47207](https://github.com/elastic/elasticsearch/pull/47207) (issue: [#41059](https://github.com/elastic/elasticsearch/issues/41059))
 - [x] Remove use_field_mapping format option for docvalue fields [#55622](https://github.com/elastic/elasticsearch/pull/55622)
 - [x] Remove deprecated SimpleQueryStringBuilder parameters [#57200](https://github.com/elastic/elasticsearch/pull/57200)
 - [x] Remove deprecated search.remote settings [#42381](https://github.com/elastic/elasticsearch/pull/42381) (issues: [#33413](https://github.com/elastic/elasticsearch/issues/33413), [#38556](https://github.com/elastic/elasticsearch/issues/38556))
 - [x] Remove deprecated sort options: nested_path and nested_filter [#42809](https://github.com/elastic/elasticsearch/pull/42809) (issue: [#27098](https://github.com/elastic/elasticsearch/issues/27098))
 - [x] Remove deprecated vector functions [#48725](https://github.com/elastic/elasticsearch/pull/48725) (issue: [#48604](https://github.com/elastic/elasticsearch/issues/48604))
 - [x] Remove support for _type in searches [#68564](https://github.com/elastic/elasticsearch/pull/68564) (issues: [#41059](https://github.com/elastic/elasticsearch/issues/41059), [#68311]
 - [x] Remove support for sparse vectors [#48781](https://github.com/elastic/elasticsearch/pull/48781) (issue: [#48368](https://github.com/elastic/elasticsearch/issues/48368))
(https://github.com/elastic/elasticsearch/issues/68311))
 - [x] Remove the object format for indices_boost [#55078](https://github.com/elastic/elasticsearch/pull/55078)
 - [x] Removes typed endpoint from search and related APIs [#41640](https://github.com/elastic/elasticsearch/pull/41640)
 - [x] Removes type from TermVectors APIs [#42198](https://github.com/elastic/elasticsearch/pull/42198) (issue: [#41059](https://github.com/elastic/elasticsearch/issues/41059))

### CODE REVIEW

**Comment by matchish** [comment]
I see that phpunit have to be updated. Code coverage not supported with php8 by this version

**Comment by hkulekci** [comment]
👍  Let me check it

**Comment by hkulekci** [comment]
Interestingly, tests passed for both versions as I tried locally. For now, with PHP 8.0.9, I tried PHPUnit 9.5.13 and 8.5.23 with coverage flag and both are working without any error.

**Comment by matchish** [comment]
Looks great to me)

**Comment by hkulekci** [comment]
I could not understand what I need to do related with`indices_boost` parameter. I think, no need to do any changes.

**Comment by matchish** [comment]
Could you point where described breaking changes in es8 for this parameter?

**Comment by hkulekci** [comment]
> Could you point where described breaking changes in es8 for this parameter?

Inside the search part : 

  - Remove the object format for indices_boost [#55078](https://github.com/elastic/elasticsearch/pull/55078)
  
https://www.elastic.co/guide/en/elasticsearch/reference/master/release-notes-8.0.0.html

**Comment by hkulekci** [comment]
I think we don't do anything. I will try to put a functional test for it. There is a parameter inside the Search class of this library, but we do not try to format the parameter's value. So, I think it is not this library's responsibility.

**Comment by matchish** [comment]
Yeah you're right. We don't check format  of indices boosts so no changes.

**Comment by matchish** [comment]
We could introduce interface for the parameter, but looks it's not the way of this library

**Comment by hkulekci** [comment]
Okay, here is the latest situation. I fetched the list from the release notes of the Elasticsearch page, and I checked the bullets one by one. I close some of them directly without changing the code because of their disinterests. Lastly, we have one issue now is related to sorting with nested fields. 

 > Remove deprecated sort options: nested_path and nested_filter https://github.com/elastic/elasticsearch/pull/42809 (issue: https://github.com/elastic/elasticsearch/issues/27098)
 
 I had not used it before. For this reason, I will investigate a little bit what the changes are. Then we can go through the PR to the main repository. 

Thanks.

**Comment by hkulekci** [comment]
Okay so, as I see, nested-related deprecation changes are already done at 7.x version. 
https://github.com/ongr-io/ElasticsearchDSL/pull/267/files

**Comment by hkulekci** [comment]
Before : 

```
POST /_search
{
   "query" : {
      "term" : { "product" : "chocolate" }
   },
   "sort" : [
       {
          "offer.price" : {
             "mode" :  "avg",
             "order" : "asc",
             "nested_path" : "offer",
             "nested_filter" : {
                "term" : { "offer.color" : "blue" }
             }
          }
       }
    ]
}
```

After : 

```
POST /_search
{
   "query" : {
      "term" : { "product" : "chocolate" }
   },
   "sort" : [
       {
          "offer.price" : {
             "mode" :  "avg",
             "order" : "asc",
             "nested": {
                "path": "offer",
                "filter": {
                   "term" : { "offer.color" : "blue" }
                }
             }
          }
       }
    ]
}
```

**Pull request merged**
